apiVersion: v1
kind: Pod
metadata:
  name: bad-pod-runasroot
spec:
  securityContext:
    runAsNonRoot: false
  containers:
    - name: root-app
      image: alpine:3.20
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      resources:
        limits:
          memory: "128Mi"
