apiVersion: v1
kind: Pod
metadata:
  name: bad-pod-no-resources
spec:
  containers:
  - name: app
    image: nginx:latest
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
