apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-no-resources
spec:
  template:
    spec:
      containers:
        - name: app
          image: nginx:latest
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
