apiVersion: v1
kind: Pod
metadata:
  name: bad-pod
spec:
  containers:
  - name: bad-container
    image: nginx:latest
    securityContext:
      runAsNonRoot: false
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - NET_RAW
    resources:
      limits:
        cpu: "100m"
    command: ["sleep", "3600"]
