apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juice-shop
  template:
    metadata:
      labels:
        app: juice-shop
    spec:
      containers:
        - name: juice-shop
          image: bkimminich/juice-shop:v19.0.0
          ports:
            - containerPort: 3000
          securityContext:
            runAsUser: 0
            privileged: true
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
