apiVersion: v1
kind: Namespace
metadata:
  annotations:
    description: "Isolated environment for Juice Shop workload with restricted PSS"
  labels:
    kubernetes.io/metadata.name: juice-shop
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
  name: juice-shop
