---
env:
  contexts:
    - name: "Juice Shop Authenticated"
      urls:
        - "http://localhost:3000"
      includePaths:
        - "http://localhost:3000.*"
      authentication:
        method: "json"
        parameters:
          loginPageUrl: "http://localhost:3000/rest/user/login"
          loginRequestUrl: "http://localhost:3000/rest/user/login"
          loginRequestBody: '{"email":"{%username%}","password":"{%password%}"}'
        verification:
          method: "response"
          loggedInRegex: "\\Qauthentication\\E"
          pollFrequency: 60
          pollUnits: "requests"
          pollUrl: ""
          pollPostData: ""
      sessionManagement:
        method: "cookie"
      users:
        - name: "admin"
          credentials:
            username: "admin@juice-sh.op"
            password: "admin123"

jobs:
  - type: spider
    parameters:
      context: "Juice Shop Authenticated"
      user: "admin"
      maxDuration: 5
      maxDepth: 5

  - type: spiderAjax
    parameters:
      context: "Juice Shop Authenticated"
      user: "admin"
      maxDuration: 10
      maxCrawlDepth: 5
      numberOfBrowsers: 2

  - type: passiveScan-wait
    parameters:
      maxDuration: 5

  - type: activeScan
    parameters:
      context: "Juice Shop Authenticated"
      user: "admin"
      maxRuleDurationInMins: 5
      maxScanDurationInMins: 30

  - type: report
    parameters:
      template: "traditional-html"
      reportDir: "/zap/wrk/zap"
      reportFile: "report-auth.html"
    risks:
      - high
      - medium
      - low
      - info

  - type: report
    parameters:
      template: "traditional-json"
      reportDir: "/zap/wrk/zap"
      reportFile: "zap-report-auth.json"
    risks:
      - high
      - medium
      - low
      - info
