---
env:
  contexts:
    - name: "juice-shop"
      urls:
        - "http://localhost:3000"
      includePaths:
        - "http://localhost:3000.*"
      authentication:
        method: "json"
        parameters:
          loginPageUrl: "http://localhost:3000/rest/user/login"
          loginRequestUrl: "http://localhost:3000/rest/user/login"
          loginRequestBody: '{"email":"admin@juice-sh.op","password":"admin123"}'
        verification:
          method: "response"
          loggedInRegex: "\\Qauthentication\\E"
          loggedOutRegex: "\\Qerror\\E"
      sessionManagement:
        method: "cookie"
      users:
        - name: "admin"
          credentials:
            username: "admin@juice-sh.op"
            password: "admin123"

jobs:
  - type: spider
    parameters:
      context: "juice-shop"
      user: "admin"
      maxDuration: 3
      
  - type: spiderAjax
    parameters:
      context: "juice-shop"
      user: "admin"
      maxDuration: 5
      
  - type: passiveScan-wait
    parameters:
      maxDuration: 3
      
  - type: report
    parameters:
      template: "traditional-html"
      reportDir: "/zap/wrk/zap"
      reportFile: "report-auth.html"
      reportTitle: "ZAP Authenticated Scan Report"
      
  - type: report
    parameters:
      template: "traditional-json"
      reportDir: "/zap/wrk/zap"
      reportFile: "zap-report-auth.json"
